### ISSUE TITLE
fix(js-packages): missing ignoreExitCode option for yarn v2 package manager

### ISSUE THREAD

**Issue by getlarge** [code-pushup/cli#877]
### What happened?

I just encountered an unexpected error while setting up the `js-packages` plugin.

Code-pushup throws the following error:
```
file:///builds/vanilla/monorepo/node_modules/@code-pushup/js-packages-plugin/bin.js:1743
    throw new Error(`JS Packages plugin: Running ${pm.name} audit failed.`);
          ^
Error: JS Packages plugin: Running yarn-modern audit failed.
    at processAudit (file:///builds/vanilla/monorepo/node_modules/@code-pushup/js-packages-plugin/bin.js:1743:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeRunner (file:///builds/vanilla/monorepo/node_modules/@code-pushup/js-packages-plugin/bin.js:1686:51)
    at async file:///builds/vanilla/monorepo/node_modules/@code-pushup/js-packages-plugin/bin.js:1761:1
Node.js v21.7.3
    at executePlugins (file:///builds/vanilla/monorepo/node_modules/@code-pushup/cli/index.js:2707:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collect (file:///builds/vanilla/monorepo/node_modules/@code-pushup/cli/index.js:2737:25)
    at async collectAndPersistReports (file:///builds/vanilla/monorepo/node_modules/@code-pushup/cli/index.js:2808:18)
    at async handler (file:///builds/vanilla/monorepo/node_modules/@code-pushup/cli/index.js:3408:7)
    at async Object.handler (file:///builds/vanilla/monorepo/node_modules/@code-pushup/cli/index.js:3619:14)
ProcessError: Error: Executing 1 plugin failed.
Error: - Plugin JS Packages (js-packages) produced the following error:
  - ProcessError
    at ChildProcess.<anonymous> (file:///builds/vanilla/monorepo/node_modules/@code-pushup/js-packages-plugin/bin.js:763:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  stderr: '',
  stdout: '{"value":"axios","children":{"ID":1098583,"Issue":"Server-Side Request Forgery in axios","URL":"https://github.com/advisories/GHSA-8hc4-vh64-cxmj","Severity":"high","Vulnerable Versions":">=1.3.2 <=1.7.3","Tree Versions":["1.6.7"],"Dependents":["frontend@workspace:."]}}\n'
}
```

Isn’t it strange that the exit code 1 is considered an error when the actual output seems valid?
Is this the exit code produced by the `yarn-plugin-outdated` ?

### What steps did you take?

Setup code-pushup with the following config:
```ts
export default {
        persist: {
            outputDir: '.code-pushup',
            format: ['json', 'md'],
        },
        plugins: [
            // ...
            await jsPackagesPlugin({
                packageManager: 'yarn-modern',
                packageJsonPaths: ['package.json'],
            }),
        ],
    },
);
```

And run the task with a package.json/yarn.lock containing dependencies with known vulnerabilities.

### Code PushUp package version

0.53.1

### What operation system are you on?

Linux

### Relevant log output

```shell

```

**Comment by getlarge** [comment]
As @matejchalk mentioned in Slack
> The ignoreExitCode is set for outdated check, but not for audit check (which is where it failed going by the logs): https://github.com/code-pushup/cli/blob/main/packages/plugin-js-packages/src/lib/runner/index.ts#L119
For audit the flag is different per package manager (off by default), but Yarn modern doesn't set it, which seems to be the source of the problem: https://github.com/code-pushup/cli/blob/main/packages/plugin-js-packages/src/lib/package-managers/yarn-modern/yarn-modern.ts#L25-L34
